name: Code Coverage

on: [push]

jobs:
  upload-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas
          pip install pylint
          pip install -U Flask
          pip install -U flask-cors
          pip install pytest
          pip install pytest-cov

      - name: Run tests and generate coverage
        run: |
          cd test
          pytest --cov=.

      - name: Upload coverage report to coveralls
        uses: coverallsapp/github-action@v2.3.4

