name: test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas
        pip install pylint
        pip install -U Flask
        pip install -U flask-cors
        pip install pytest
    - name: Running test cases for api
      run: |
        chmod +x ./.github/test.sh;
        bash test.sh;
          