name: test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas
        pip install pylint
        pip install -U Flask
        pip install -U flask-cors
        pip install -U flask-sqlalchemy
        pip install -U flask-login
        pip install -U requests
        pip install -U pytest
        pip install -U pytest-cov
    - name: Running test cases for api
      run: |
        chmod +x ${GITHUB_WORKSPACE}/.github/test.sh;
        bash ${GITHUB_WORKSPACE}/.github/test.sh ${GITHUB_WORKSPACE};
        coverage combine {GITHUB_WORKSPACE}/src backend/.coverage .coverage;
    - name: Upload coverage report to coveralls
        uses: coverallsapp/github-action@v2.3.4


          